name: add user to repo
on:
  workflow_dispatch:
jobs:
    build:
    runs-on: ubuntu-latest
    steps:
   - name: checkout repo
     uses: actions/checkout@v2

   - name:  message
     run: 
       Welcome to github actions
       
     

