name: list repos
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  listrepos:
    runs-on: ubuntu-latest
    steps:
        - name: Fetch list of repos
          run: |
            org="jhdevops"
            touch repo_list.txt
            
              repos=$(curl -s -H "Authorization: token ${{ secrets.secret_token }}" \
               "https://api.github.com/orgs/$org/repos?page=$page" | jq -r '.[] | .name' | tr -d '"')
              
              echo "$repos" >> repo_list.txt
              
            
            cat repo_list.txt
         
      
